"""Gyration Ratio

Revision ID: 508fd020fba3
Revises: 
Create Date: 2025-11-26 22:00:57.043972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508fd020fba3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyration_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atoms', sa.Integer(), nullable=False),
    sa.Column('cube_gr', sa.Float(), nullable=True),
    sa.Column('sphere_gr', sa.Float(), nullable=True),
    sa.Column('random_gr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gyration_ratio')
    # ### end Alembic commands ###
